import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing. Please check your environment configuration.");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Edits an image using Gemini 2.5 Flash Image ("Nano Banana")
 * @param base64Image The base64 string of the image (without the data prefix usually)
 * @param mimeType The mime type of the image (e.g., image/png)
 * @param prompt The user's editing instruction
 * @returns Object containing the base64 string of the generated image and its mimeType
 */
export const editImageWithGemini = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<{ data: string; mimeType: string }> => {
  const ai = getClient();
  
  // Robust base64 extraction: split by comma to remove data URI scheme if present
  // Also remove any whitespace/newlines which can cause invalid argument errors
  const base64Data = (base64Image.includes(',') ? base64Image.split(',')[1] : base64Image).replace(/\s/g, '');

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Nano Banana
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Note: responseMimeType and responseSchema are NOT supported for Nano Banana models
    });

    // Iterate through parts to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    
    if (!parts) {
      throw new Error("No content generated by the model.");
    }

    let generatedImageBase64: string | null = null;
    let generatedMimeType: string = 'image/jpeg'; // Default to jpeg if not specified

    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        generatedImageBase64 = part.inlineData.data;
        if (part.inlineData.mimeType) {
          generatedMimeType = part.inlineData.mimeType;
        }
        break; 
      }
    }

    if (!generatedImageBase64) {
       // If no image found, check if there is text explaining why
       const textPart = parts.find(p => p.text);
       if (textPart) {
         throw new Error(`Model returned text instead of image: ${textPart.text}`);
       }
       throw new Error("Model did not return a valid image.");
    }

    return { data: generatedImageBase64, mimeType: generatedMimeType };

  } catch (error) {
    console.error("Gemini Edit Error:", error);
    throw error;
  }
};